import psycopg2
import sys

from config import password
from config import database
from config import user

# SQL command to get the names of all the athletes from a specified NOC
def get_query1(noc):
	return "SELECT DISTINCT athletes.name, athletes.team_id, teams.id from athletes, teams WHERE teams.noc = {}" \
		 " and athletes.team_id = teams.id".format(noc)

# SQL command to list all the NOCs and the number of gold medals they have won, in decreasing order of the number of gold medals.
def get_query2(noc, medal):
	return "SELECT athletes.name, teams.id FROM athletes, teams WHERE teams.noc = {}" \
		   " AND athletes.medal = '{}' AND athletes.team_id = teams.id".format(noc, medal)

# SQL command to list the names of all the athletes that competed in wrestling
query3 = "SELECT DISTINCT athletes.name, athletes.event FROM athletes WHERE event = 'Wrestling' and athletes.event = event"

# Connect to the database
try:
	connection = psycopg2.connect(database=database, user=user, password=password)
except Exception as e:
	print(e)
	exit()

noc = "USA"

# Query the database, leaving you with a "cursor"--an object you can
# use to iterate over the rows generated by your query.
try:
	cursor = connection.cursor()
	cursor.execute(get_query1("%s"), (noc, ))
except Exception as e:
	print(e)
	exit()

# We have a cursor now. Iterate over its rows to print the results.
print('===== Names of all the athletes from the USA =====')
for row in cursor:
	print(row[0], row[1])
print()

def get_medal_count(noc, medal):
	# Do query2.
	try:
		cursor.execute(get_query2(noc, medal), (noc, ))
	except Exception as e:
		print(e)
		exit()

	n = 0
	for i in cursor:  # dumb but works
		n += 1

	return n

# # Get list of NOCs.
# try:
#     cursor.execute(query, (search_string,))
# except Exception as e:
#     print(e)
#     exit()


# try:
# 	cursor = connection.cursor()
# 	cursor.execute("SELECT teams.noc FROM teams")
# except Exception as e:
# 	print(e)
# 	exit()

# noc_list = [n for n in cursor]
# print("noc list!!!!")
# print(noc_list)

# print("Number of gold medals won by {} is {}.".format(noc, get_medal_count(noc, "Gold"))

# Now do query3.
try:
    cursor.execute(query3)
except Exception as e:
    print(e)
    exit()